### ISSUE TITLE
fail to bind with lang cffi under python3

### ISSUE THREAD

**Issue by lifei** [go-python/gopy#145]
### Errors

```
panic: gopy: could not find pkg-config file (no python.pc installed?)

goroutine 1 [running]:
github.com/go-python/gopy/bind.(*goGen).genPreamble(0xc420187680)
        /usr/local/src/github.com/go-python/gopy/bind/gengo.go:1112 +0x5e9
github.com/go-python/gopy/bind.(*goGen).gen(0xc420187680, 0xc4201876c0, 0x1)
        /usr/local/src/github.com/go-python/gopy/bind/gengo.go:191 +0x43
github.com/go-python/gopy/bind.GenGo(0x8a2900, 0xc42000c5a0, 0xc42000e300, 0xc42008a8c0, 0x2, 0xc4201ae56a, 0x5)
        /usr/local/src/github.com/go-python/gopy/bind/bind.go:93 +0x142
main.genPkg(0xc4200138c0, 0x13, 0xc42008a8c0, 0x7312a5, 0x2, 0x0, 0x0)
        /usr/local/src/github.com/go-python/gopy/gen.go:90 +0x7ce
main.gopyRunCmdBind(0xc42009a6c0, 0xc42000e0b0, 0x1, 0x1, 0x0, 0x0)
        /usr/local/src/github.com/go-python/gopy/cmd_bind.go:120 +0x7f4
github.com/gonuts/commander.(*Command).Dispatch(0xc42009a6c0, 0xc42000e0a0, 0x2, 0x2, 0xc420039f01, 0x69c833)
        /usr/local/src/github.com/gonuts/commander/commands.go:221 +0x27a
github.com/gonuts/commander.(*Command).Dispatch(0xc42009a7e0, 0xc42000e090, 0x3, 0x3, 0x0, 0x0)
        /usr/local/src/github.com/gonuts/commander/commands.go:187 +0x162
main.main()
        /usr/local/src/github.com/go-python/gopy/main.go:42 +0x123
```

### To reproduce

1. build a docker image with following `Dockerfile`

```
FROM python
ADD go1.9.linux-amd64.tar.gz /usr/local
ENV PATH "$PATH:/usr/local/go/bin"
ENV GOPATH /usr/local
RUN go get github.com/go-python/gopy
RUN pip install cffi
```

2. start a container and run cmd: `gopy bind -lang=cffi github.com/go-python/gopy/_examples/hi`.

**Comment by rcoreilly** [comment]
for old version, closing
