### ISSUE TITLE
pkg: ImportError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by itswcg** [go-python/gopy#262]
I use command
`gopy pkg -output=out -vm=python3 github.com/go-python/gopy/_examples/hi `
`cd out && make install-pkg`

then 
```
>>> from hi impot hi
  File "<stdin>", line 1
    from hi impot hi
            ^
SyntaxError: invalid syntax
>>> from hi import hi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/out/hi/hi.py", line 20, in <module>
    from ..hi import _hi
ImportError: attempted relative import beyond top-level package
```

**Comment by DariusSG** [comment]
Change "from ..hi import _hi" to "from . import _hi"
