### ISSUE TITLE
bind: support for go.interfaces

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#34]
right now, the following package:

``` go
package iface

type Iface interface {
    F()
}
```

fails with:

``` sh
sh> gopy bind ./_examples/iface
panic: unhandled named-type: [*types.TypeName]
&types.Named{obj:(*types.TypeName)(0xc8200b84b0), underlying:(*types.Interface)(0xc8200b8500), methods:[]*types.Func(nil)}


goroutine 1 [running]:
github.com/go-python/gopy/bind.(*symtab).addType(0xc820011400, 0x7f3629be9348, 0xc8200b84b0, 0x7f3629be9538, 0xc82000b470)
    /home/binet/dev/go/root/path/src/github.com/go-python/gopy/bind/symtab.go:360 +0xdc4
github.com/go-python/gopy/bind.(*symtab).addSymbol(0xc820011400, 0x7f3629be9348, 0xc8200b84b0)
    /home/binet/dev/go/root/path/src/github.com/go-python/gopy/bind/symtab.go:291 +0x9d8
github.com/go-python/gopy/bind.(*Package).process(0xc8200af560, 0x0, 0x0)
    /home/binet/dev/go/root/path/src/github.com/go-python/gopy/bind/package.go:176 +0x12bf
github.com/go-python/gopy/bind.NewPackage(0xc8200b8410, 0xc8200bc0e0, 0x29, 0x0, 0x0)
    /home/binet/dev/go/root/path/src/github.com/go-python/gopy/bind/package.go:42 +0x388
main.newPackageFrom(0xc8200300b0, 0x1, 0x1, 0xc82009cc80, 0xc8200b6000, 0xc8200300b0, 0x0, 0x0)
    /home/binet/dev/go/root/path/src/github.com/go-python/gopy/gen.go:191 +0x24c
main.newPackage(0x7fff034ca8c8, 0x11, 0xc820012044, 0x0, 0x0)
    /home/binet/dev/go/root/path/src/github.com/go-python/gopy/gen.go:164 +0x2f9
main.gopyRunCmdBind(0xc820016900, 0xc82000a380, 0x1, 0x1, 0x0, 0x0)
    /home/binet/dev/go/root/path/src/github.com/go-python/gopy/cmd_bind.go:73 +0x4eb
github.com/gonuts/commander.(*Command).Dispatch(0xc820016900, 0xc82000a380, 0x1, 0x1, 0x0, 0x0)
    /home/binet/dev/go/root/path/src/github.com/gonuts/commander/commands.go:221 +0x7e2
github.com/gonuts/commander.(*Command).Dispatch(0xc820016a20, 0xc82000a370, 0x2, 0x2, 0x0, 0x0)
    /home/binet/dev/go/root/path/src/github.com/gonuts/commander/commands.go:187 +0x1f9
main.main()
    /home/binet/dev/go/root/path/src/github.com/go-python/gopy/main.go:38 +0x1fe

```

**Comment by rcoreilly** [comment]
for old version, closing
