### ISSUE TITLE
bind: support funcs taking pointers

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#45]
right now:

``` go
package pointers
type S struct {
    Value int
}

// Inc increments the value of s
func Inc(s *S) {
    s.Value++
}
```

results in:

``` python
>>> import pointers as p
>>> s = p.S(2)
>>> p.Inc(s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x2 pc=0x7f1cc7c47fe7]

goroutine 17 [running, locked to thread]:
github.com/go-python/gopy/_examples/pointers.Inc(0x2)
    github.com/go-python/gopy/_examples/pointers/pointers.go:18 +0x7a
main.cgo_func_pointers_Inc(0xc82000a340)
    tmp/gopy-586713227/pointers.go:151 +0x26

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
    go/src/runtime/asm_amd64.s:1696 +0x1
Aborted (core dumped)
```

that's because of the following `cgo` code:

``` go
//export cgo_func_pointers_Inc
// cgo_func_pointers_Inc wraps pointers.Inc
func cgo_func_pointers_Inc(s cgo_type_pointers_S) () {
    pointers.Inc(*(**pointers.S)(unsafe.Pointer(s)))
}
```

which should, instead, read:

``` go
//export cgo_func_pointers_Inc
// cgo_func_pointers_Inc wraps pointers.Inc
func cgo_func_pointers_Inc(s cgo_type_pointers_S) () {
    pointers.Inc((*pointers.S)(unsafe.Pointer(s)))
}
```

**Comment by sbinet** [comment]
this may need a proper `codegen` refactoring...

**Comment by phil-mansfield** [comment]
Is this related to similar behavior in which structs cannot contain pointer fields, or is it distinct enough to warrant a separate issue?

The following package

```
package ptr

type T struct {
    P *int
}
```

fails with

```
$ go build && gopy bind --lang=py2 .
2015/08/31 10:23:13 work: /var/folders/j0/l297p36x68dfmcrh07jptj200000gn/T/gopy-005966317
# _/private/var/folders/j0/l297p36x68dfmcrh07jptj200000gn/T/gopy-005966317
./ptr.c:363:20: error: use of undeclared identifier 'int64_tType'
./ptr.c:368:13: error: use of undeclared identifier 'int64_tType'
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/object.h:767:18: note: expanded from macro 'Py_INCREF'
./ptr.c:369:48: error: use of undeclared identifier 'int64_tType'
2015/08/31 10:23:15 error dispatching command: exit status 2
```

**Comment by sbinet** [comment]
yeah, it's probably the same...

**Comment by kellrott** [comment]
The error trace for _examples/pointers is now

```
2015/08/31 23:00:22 work: /var/folders/sm/824x9wpx5612kvq00n4rmppn6j08ln/T/gopy-863290649
panic: interface conversion: types.Type is *types.Pointer, not *types.Named

goroutine 1 [running]:
github.com/go-python/gopy/bind.(*cpyGen).genTypeMethods(0x82067f590, 0x820692000)
	/Users/ellrott/workspaces/golang/src/github.com/go-python/gopy/bind/gencpy_type.go:372 +0x120a
github.com/go-python/gopy/bind.(*cpyGen).genType(0x82067f590, 0x820692000)
	/Users/ellrott/workspaces/golang/src/github.com/go-python/gopy/bind/gencpy_type.go:59 +0xce0
github.com/go-python/gopy/bind.(*cpyGen).gen(0x82067f590, 0x0, 0x0)
	/Users/ellrott/workspaces/golang/src/github.com/go-python/gopy/bind/gencpy.go:184 +0x32c9
github.com/go-python/gopy/bind.GenCPython(0x88207781e8, 0x8205f0200, 0x8205d4580, 0x820652d20, 0x2, 0x0, 0x0)
	/Users/ellrott/workspaces/golang/src/github.com/go-python/gopy/bind/bind.go:38 +0x2a4
main.genPkg(0x8205d5c80, 0x3f, 0x820652d20, 0x8205d29d0, 0x3, 0x0, 0x0)
	/Users/ellrott/workspaces/golang/src/github.com/go-python/gopy/gen.go:62 +0x12d0
main.gopyRunCmdBind(0x820638a20, 0x8205cc230, 0x1, 0x1, 0x0, 0x0)
	/Users/ellrott/workspaces/golang/src/github.com/go-python/gopy/cmd_bind.go:108 +0xd18
github.com/gonuts/commander.(*Command).Dispatch(0x820638a20, 0x8205cc230, 0x1, 0x1, 0x0, 0x0)
	/Users/ellrott/workspaces/golang/src/github.com/gonuts/commander/commands.go:221 +0x7e2
github.com/gonuts/commander.(*Command).Dispatch(0x820638b40, 0x8205cc220, 0x2, 0x2, 0x0, 0x0)
	/Users/ellrott/workspaces/golang/src/github.com/gonuts/commander/commands.go:187 +0x1f9
main.main()
	/Users/ellrott/workspaces/golang/src/github.com/go-python/gopy/main.go:38 +0x1fe
```

So at some point the symbol.kind value is being set as |= skNamed. The only point that ever happens is at https://github.com/go-python/gopy/blob/master/bind/symtab.go#L380

Not quite understanding why this is happening.

**Comment by rcoreilly** [comment]
for old version, closing
