### ISSUE TITLE
bind: support for all builtin types

### ISSUE THREAD

**Issue by phil-mansfield** [go-python/gopy#59]
Currently `rune`, `uintptr`, and `unsafe.Pointer` are not supported.

The package 

```
package types
var X rune
```

fails with 

```
$ go build && gopy bind --lang=py2 .
2015/08/31 21:18:05 work: /var/folders/j0/l297p36x68dfmcrh07jptj200000gn/T/gopy-283258537
# _/private/var/folders/j0/l297p36x68dfmcrh07jptj200000gn/T/gopy-283258537
./types.c:150:2: error: use of undeclared identifier 'GoRune'
./types.c:152:2: error: use of undeclared identifier 'c_gopy_ret'
./types.c:154:29: error: use of undeclared identifier 'cgopy_cnv_c2py_rune'
./types.c:161:2: error: use of undeclared identifier 'GoRune'
./types.c:163:36: error: use of undeclared identifier 'cgopy_cnv_py2c_rune'
./types.c:168:23: error: use of undeclared identifier 'c_X'
2015/08/31 21:18:06 error dispatching command: exit status 2
```

The package 

```
package types
var X uintptr
```

fails with

```
$ go build && gopy bind --lang=py2 .
panic: builtin type not already known [uintptr]!

goroutine 1 [running]:
github.com/go-python/gopy/bind.(*symtab).addType(0x8205cf000, 0x8820776a40, 0x820621ef0, 0x8820776318, 0x53dc00)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/symtab.go:363 +0x7c9
github.com/go-python/gopy/bind.(*symtab).addSymbol(0x8205cf000, 0x8820776a40, 0x820621ef0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/symtab.go:308 +0x456
github.com/go-python/gopy/bind.(*Package).process(0x820648dc0, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/package.go:179 +0x26dd
github.com/go-python/gopy/bind.NewPackage(0x820621e50, 0x820661880, 0x14, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/package.go:44 +0x390
main.newPackageFrom(0x8205e80a0, 0x1, 0x1, 0x820648c80, 0x820662000, 0x8205e80a0, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/gen.go:209 +0x3bf
main.newPackage(0x7fff5fbffa5d, 0x1, 0x8205d2064, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/gen.go:179 +0x638
main.gopyRunCmdBind(0x8206327e0, 0x8205ca2f0, 0x1, 0x1, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/cmd_bind.go:73 +0x4eb
github.com/gonuts/commander.(*Command).Dispatch(0x8206327e0, 0x8205ca2f0, 0x1, 0x1, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/gonuts/commander/commands.go:221 +0x7e2
github.com/gonuts/commander.(*Command).Dispatch(0x820632900, 0x8205ca2d0, 0x3, 0x3, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/gonuts/commander/commands.go:187 +0x1f9
main.main()
    /Users/phil/code/go/src/github.com/go-python/gopy/main.go:38 +0x1fe
```

The package 

```
package types
import "unsafe"
var X unsafe.Pointer
```

fails with

```
$ go build && gopy bind --lang=py2 .
panic: builtin type not already known [unsafe.Pointer]!

goroutine 1 [running]:
github.com/go-python/gopy/bind.(*symtab).addType(0x8205cf180, 0x8820776b70, 0x820621ef0, 0x8820776318, 0x53dcc0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/symtab.go:363 +0x7c9
github.com/go-python/gopy/bind.(*symtab).addSymbol(0x8205cf180, 0x8820776b70, 0x820621ef0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/symtab.go:308 +0x456
github.com/go-python/gopy/bind.(*Package).process(0x820648e60, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/package.go:179 +0x26dd
github.com/go-python/gopy/bind.NewPackage(0x820621e50, 0x820661880, 0x14, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/package.go:44 +0x390
main.newPackageFrom(0x8205e80b0, 0x1, 0x1, 0x820648d20, 0x820662000, 0x8205e80b0, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/gen.go:209 +0x3bf
main.newPackage(0x7fff5fbffa5d, 0x1, 0x8205d2064, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/gen.go:179 +0x638
main.gopyRunCmdBind(0x8206326c0, 0x8205ca2f0, 0x1, 0x1, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/cmd_bind.go:73 +0x4eb
github.com/gonuts/commander.(*Command).Dispatch(0x8206326c0, 0x8205ca2f0, 0x1, 0x1, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/gonuts/commander/commands.go:221 +0x7e2
github.com/gonuts/commander.(*Command).Dispatch(0x8206327e0, 0x8205ca2d0, 0x3, 0x3, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/gonuts/commander/commands.go:187 +0x1f9
main.main()
    /Users/phil/code/go/src/github.com/go-python/gopy/main.go:38 +0x1fe
```

Probably the best thing to hand a Python program that asks for an `unsafe.Pointer` is a `ctypes.c_void_p`.

**Comment by sbinet** [comment]
yep, that (using `ctypes.c_void_p`) or creating a `PyCapsule`.

**Comment by rcoreilly** [comment]
for old version, closing
