### ISSUE TITLE
panic: could not look-up "[]string"!

### ISSUE THREAD

**Issue by prashanthellina** [go-python/gopy#63]
File `/tmp/dummy/dummy.go` has,

``` go
package dummy

func DoSomething(m map[int][]string) {
}
```

``` bash
gopy gen dummy
panic: could not look-up "[]string"!


goroutine 1 [running]:
github.com/go-python/gopy/bind.(*symtab).addMapType(0xc8200aae80, 0xc8200b2460, 0x7f98fa07a378, 0xc8200b25a0, 0x7f98fa07a318, 0xc8200aaae0, 0x88, 0xc8200aaf20, 0x16, 0xc8200ae590, ...)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/symtab.go:501 +0xa35
github.com/go-python/gopy/bind.(*symtab).addType(0xc8200aae80, 0x7f98fa07a378, 0xc8200b25a0, 0x7f98fa07a318, 0xc8200aaae0)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/symtab.go:444 +0x326
github.com/go-python/gopy/bind.(*symtab).processTuple(0xc8200aae80, 0xc8200aab20)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/symtab.go:349 +0x149
github.com/go-python/gopy/bind.(*symtab).addSymbol(0xc8200aae80, 0x7f98fa0be408, 0xc8200b2500)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/symtab.go:329 +0xceb
github.com/go-python/gopy/bind.(*Package).process(0xc8200c8140, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/package.go:179 +0x26dd
github.com/go-python/gopy/bind.NewPackage(0xc8200b2460, 0xc8200ca0e0, 0x5, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/package.go:44 +0x390
main.newPackageFrom(0xc8200b8040, 0x1, 0x1, 0xc8200c8000, 0xc8200b6000, 0xc8200b8040, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/gen.go:209 +0x3bf
main.newPackage(0x7fff8ae10770, 0x5, 0xc820010054, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/gen.go:179 +0x638
main.gopyRunCmdGen(0xc820014b40, 0xc82000a200, 0x1, 0x1, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/cmd_gen.go:75 +0x588
github.com/gonuts/commander.(*Command).Dispatch(0xc820014b40, 0xc82000a200, 0x1, 0x1, 0x0, 0x0)
        /home/prashanth/go/src/github.com/gonuts/commander/commands.go:221 +0x7e2
github.com/gonuts/commander.(*Command).Dispatch(0xc820014d80, 0xc82000a1f0, 0x2, 0x2, 0x0, 0x0)
        /home/prashanth/go/src/github.com/gonuts/commander/commands.go:187 +0x1f9
main.main()
        /home/prashanth/go/src/github.com/go-python/gopy/main.go:38 +0x1fe
```

**Comment by rcoreilly** [comment]
for old version, closing
