### ISSUE TITLE
bind: support for empty interfaces

### ISSUE THREAD

**Issue by prashanthellina** [go-python/gopy#65]
The package

``` go
package dummy

func DoSomething(x interface{}) {
}
```

Fails with

``` bash
panic: unhandled obj [*types.Var]
type [&types.Interface{methods:[]*types.Func(nil), embeddeds:[]*types.Named(nil), allMethods:[]*types.Func(nil)}]

goroutine 1 [running]:
github.com/go-python/gopy/bind.(*symtab).addType(0xc82000f520, 0x7fd44a4fdaa8, 0xc820069b30, 0x7fd44a4fd498, 0xc820069ae0)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/symtab.go:447 +0x522
github.com/go-python/gopy/bind.(*symtab).processTuple(0xc82000f520, 0xc82000f1c0)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/symtab.go:349 +0x149
github.com/go-python/gopy/bind.(*symtab).addSymbol(0xc82000f520, 0x7fd44a4fd408, 0xc820069a40)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/symtab.go:329 +0xceb
github.com/go-python/gopy/bind.(*Package).process(0xc820094d20, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/package.go:179 +0x26dd
github.com/go-python/gopy/bind.NewPackage(0xc8200699a0, 0xc8200a7880, 0x5, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/bind/package.go:44 +0x390
main.newPackageFrom(0xc82002e0a0, 0x1, 0x1, 0xc820094be0, 0xc8200a8000, 0xc82002e0a0, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/gen.go:209 +0x3bf
main.newPackage(0x7ffe8daf3770, 0x5, 0xc820010054, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/gen.go:179 +0x638
main.gopyRunCmdGen(0xc820014a20, 0xc82000a200, 0x1, 0x1, 0x0, 0x0)
        /home/prashanth/go/src/github.com/go-python/gopy/cmd_gen.go:75 +0x588
github.com/gonuts/commander.(*Command).Dispatch(0xc820014a20, 0xc82000a200, 0x1, 0x1, 0x0, 0x0)
        /home/prashanth/go/src/github.com/gonuts/commander/commands.go:221 +0x7e2
github.com/gonuts/commander.(*Command).Dispatch(0xc820014c60, 0xc82000a1f0, 0x2, 0x2, 0x0, 0x0)
        /home/prashanth/go/src/github.com/gonuts/commander/commands.go:187 +0x1f9
main.main()
        /home/prashanth/go/src/github.com/go-python/gopy/main.go:38 +0x1fe
```

**Comment by rcoreilly** [comment]
for old version, closing
