### ISSUE TITLE
pkgconfig: better error message, better macosx support

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#72]
from golang-nuts:

```
Hi, I was just testing out gopy but I'm not able to run bind on any of the examples. I get an error message asking if python.pc is installed. I'm not sure what python.pc is but I verified cython is installed. gopy gen works for the examples.

$ gopy bind github.com/go-python/gopy/_examples/hi
panic: gopy: could not find pkg-config file (no python.pc installed?)

goroutine 1 [running]:
github.com/go-python/gopy/bind.(*goGen).genPreamble(0xc82012d598)
    /Users/amcfarlin/Projects/gospace/src/github.com/go-python/gopy/bind/gengo.go:962 +0x351
github.com/go-python/gopy/bind.(*goGen).gen(0xc82012d598, 0x0, 0x0)
    /Users/amcfarlin/Projects/gospace/src/github.com/go-python/gopy/bind/gengo.go:141 +0x45
github.com/go-python/gopy/bind.GenGo(0x7931c0, 0xc82007e538, 0xc8200704c0, 0xc8200b2b40, 0x2, 0x0, 0x0)
    /Users/amcfarlin/Projects/gospace/src/github.com/go-python/gopy/bind/bind.go:65 +0x1ad
main.genPkg(0xc8200e1540, 0x3f, 0xc8200b2b40, 0x382980, 0x2, 0x0, 0x0)
    /Users/amcfarlin/Projects/gospace/src/github.com/go-python/gopy/gen.go:78 +0x57b
main.gopyRunCmdBind(0xc820096900, 0xc820078170, 0x1, 0x1, 0x0, 0x0)
    /Users/amcfarlin/Projects/gospace/src/github.com/go-python/gopy/cmd_bind.go:113 +0xd93
github.com/gonuts/commander.(*Command).Dispatch(0xc820096900, 0xc820078170, 0x1, 0x1, 0x0, 0x0)
    /Users/amcfarlin/Projects/gospace/src/github.com/gonuts/commander/commands.go:221 +0x7e2
github.com/gonuts/commander.(*Command).Dispatch(0xc820096a20, 0xc820078160, 0x2, 0x2, 0x0, 0x0)
    /Users/amcfarlin/Projects/gospace/src/github.com/gonuts/commander/commands.go:187 +0x1f9
main.main()
    /Users/amcfarlin/Projects/gospace/src/github.com/go-python/gopy/main.go:42 +0x1fe
```

which was solved by manually adding `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig` to `PKG_CONFIG_PATH`

This should be done automatically by `gopy`.

**Comment by c-goosen** [comment]
Also an issue in go version go1.5.2 linux/amd64
Using golang:latest docker image with go-py installed. 
Any suggestions for a workaround in the mean-time?

**Comment by c-goosen** [comment]
Sorry an error on my part. apt-get install python-dev solves the issue. 
Maybe suggest this in the install instructions?

**Comment by sbinet** [comment]
if you are using `docker`, you could perhaps directly use the container we are providing, which should have everything needed to run `gopy bind` inside:
 https://github.com/go-python/gopy#binding-generation-using-docker-for-cross-platform-builds
 https://github.com/go-python/gopy/blob/master/Dockerfile

hth,
-s

**Comment by rcoreilly** [comment]
for old version, closing
